services:
  - type: web
    name: mediadrop
    runtime: image
    repo: https://github.com/Nissay8z/mediadrop   # à remplacer par l'URL de ton dépôt
    plan: free
    envVars:
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
    dockerfilePath: ./Dockerfile
    dockerContext: .
